name: Publish Latest Videos
on:
    schedule:
        - cron: '00 23 * * *'
    pull_request:
        branches:
            - master
 
jobs:
    publish-latest:
        runs-on: ubuntu-latest
        env: 
            PLAYLIST_ID: 'UUq8slAGrCXTjEy1Kp-Y2JwQ'
            API_KEY: ${{ secrets.API_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_USER: ${{ secrets.GH_USER }}
            GH_EMAIL: ${{ secrets.GH_EMAIL }}
        steps:
            - uses: actions/checkout@v2
              with:
                token: ${{secrets.GITHUB_TOKEN}}
            - name: "build container"
              run: |
                docker build -t live-study .
                git config --local user.name "Travis CI"
                git config --local user.email "ben@lerchin.com"
                git remote rm origin
                git remote add origin "https://mandiberg:$GITHUB_TOKEN@github.com/mandiberg/live-study.git"
                git pull origin master
                docker run -v $(pwd)/data:/root/mandiberg-painting/data\
                    -e API_KEY -e PLAYLIST_ID \
                    live-study:latest python getYoutube.py
                export TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
                git add -u 
                git diff-index --quiet HEAD || git commit -m "Adding results on $TIMESTAMP"
                git push origin master

