name: Publish Latest Videos
on:
    schedule:
        - cron: '00 23 * * *'
    pull_request:
        branches:
            - master
 
jobs:
    publish-latest:
        runs-on: ubuntu-latest
        container: python:3.6.7
        env: 
            PLAYLIST_ID: 'UUq8slAGrCXTjEy1Kp-Y2JwQ'
            API_KEY: ${{ secrets.API_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_USER: ${{ secrets.GH_USER }}
            GH_EMAIL: ${{ secrets.GH_EMAIL }}
        steps:
            - name: "update git"
              run: |
                apt-get update
                apt-get install -y software-properties-common
                add-apt-repository ppa:git-core/ppa
                apt-get update
                apt-get install -yf git
            - name: Install dependencies
              run: pip3 install -U python-dotenv==0.1.5 requests==2.7.0
            - uses: actions/checkout@v2
              with:
                token: ${{secrets.GITHUB_TOKEN}}
            - name: Pull videos
              run: python getYoutube.py
            - name: Push files
              uses: EndBug/add-and-commit@v9
              with:
                add: "data/videos.json"
                author_name: "${{secrets.GH_USER}}"
                author_email: "${{secrets.GH_EMAIL}}"
                message: "Adding results on $(date +'%Y%m%d-%H%M%S')"
